
const TITLE = 'Hackathon'
const USER_ID = 'WarrenAnderson4036'
const CAMERA_SCREEN_TITLE = 'Video'
const FRIENDS_SCREEN_TITLE = 'Friends'
const FRIENDS_POSTS_SCREEN_TITLE = 'Friend Post'
const NEW_POST_TITLE = 'New Post'

export {
  TITLE,
  USER_ID,
  CAMERA_SCREEN_TITLE,
  FRIENDS_SCREEN_TITLE,
  FRIENDS_POSTS_SCREEN_TITLE,
  NEW_POST_TITLE,
}